# Set to a random string to identify your server network. It must be set to
# the same value on all your servers. You must use a secure random value,
# or an attacker can change server placeholders for your network.
# Example: x0b7b2qeml6cZjXRJgDevmc5hNV (generate your own!)
network-id: null

# Set this to the name of this server, exactly like in the BungeeCord config.
server-name: null


# -------- Advanced users only ------------

# List of servers to use for exchanging server information. By default,
# public servers are used. If you wish, you can host your own. Placeholders
# are sent to all servers listed here.
placeholder-servers:
  - https://ssx1.rslot.nl
  - https://ssx2.kwiknet.nl

# How often the connector plugin sends placeholders, in seconds.
send-interval: 5

# Set to true to enable verbose logging
debug: false
