name: SSX-Connector
main: xyz.derkades.ssx_connector.Main
version: '@project.version@'
author: Derkades
description: 'Addon plugin for ServerSelectorX'
api-version: 1.13

commands:
  ssxc:
    aliases: [serverselectorxconnector, ssxconnector]
    usage: |
      /ssxc reload/rl - Reload configuration files
      /ssxc addons - List installed addons
      /ssxc placeholders <addon> - List placeholders provided by the given addon
      /ssxc status - Show the last time data has been sent for each address
      /ssxc count [duration] - Count the number of placeholders collected in a specific time